ALTER TABLE IF EXISTS ONLY public.staff DROP CONSTRAINT IF EXISTS fk_staff_role;
ALTER TABLE IF EXISTS ONLY public.staff DROP CONSTRAINT IF EXISTS fk_staff_position;
ALTER TABLE IF EXISTS ONLY public.staff DROP CONSTRAINT IF EXISTS fk_staff_dept;
ALTER TABLE IF EXISTS ONLY public.session DROP CONSTRAINT IF EXISTS fk_session_staff;
ALTER TABLE IF EXISTS ONLY public.role_auth DROP CONSTRAINT IF EXISTS fk_role_auth_role;
ALTER TABLE IF EXISTS ONLY public.role_auth DROP CONSTRAINT IF EXISTS fk_role_auth_auth;
ALTER TABLE IF EXISTS ONLY public.positions DROP CONSTRAINT IF EXISTS fk_position_role;
ALTER TABLE IF EXISTS ONLY public.positions DROP CONSTRAINT IF EXISTS fk_position_head;
ALTER TABLE IF EXISTS ONLY public.positions DROP CONSTRAINT IF EXISTS fk_position_dept;
ALTER TABLE IF EXISTS ONLY public.departaments DROP CONSTRAINT IF EXISTS fk_dept_head_od_dept;
ALTER TABLE IF EXISTS ONLY public.departaments DROP CONSTRAINT IF EXISTS fk_dept_head_dept;
ALTER TABLE IF EXISTS ONLY public.stats_switches DROP CONSTRAINT IF EXISTS stats_switches_pkey;
ALTER TABLE IF EXISTS ONLY public.stats DROP CONSTRAINT IF EXISTS stats_pkey;
ALTER TABLE IF EXISTS ONLY public.staff DROP CONSTRAINT IF EXISTS staff_pkey;
ALTER TABLE IF EXISTS ONLY public.session DROP CONSTRAINT IF EXISTS session_pkey;
ALTER TABLE IF EXISTS ONLY public.roles DROP CONSTRAINT IF EXISTS roles_pkey;
ALTER TABLE IF EXISTS ONLY public.role_auth DROP CONSTRAINT IF EXISTS role_auth_pkey;
ALTER TABLE IF EXISTS ONLY public.positions DROP CONSTRAINT IF EXISTS positions_pkey;
ALTER TABLE IF EXISTS ONLY public.departaments DROP CONSTRAINT IF EXISTS departaments_pkey;
ALTER TABLE IF EXISTS ONLY public.authorities DROP CONSTRAINT IF EXISTS authorities_pkey;
ALTER TABLE IF EXISTS public.staff ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.roles ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.positions ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.departaments ALTER COLUMN id DROP DEFAULT;
DROP TABLE IF EXISTS public.stats_switches;
DROP SEQUENCE IF EXISTS public.stats_switch_id_seq;
DROP VIEW IF EXISTS public.stats_records;
DROP SEQUENCE IF EXISTS public.stats_details_id_seq;
DROP TABLE IF EXISTS public.stats;
DROP SEQUENCE IF EXISTS public.stats_id_seq;
DROP VIEW IF EXISTS public.staff_roles;
DROP VIEW IF EXISTS public.staff_login;
DROP SEQUENCE IF EXISTS public.staff_id_seq;
DROP TABLE IF EXISTS public.staff;
DROP TABLE IF EXISTS public.session;
DROP SEQUENCE IF EXISTS public.roles_id_seq;
DROP TABLE IF EXISTS public.roles;
DROP TABLE IF EXISTS public.role_auth;
DROP SEQUENCE IF EXISTS public.positions_id_seq;
DROP TABLE IF EXISTS public.positions;
DROP SEQUENCE IF EXISTS public.hibernate_sequence;
DROP SEQUENCE IF EXISTS public.departaments_id_seq;
DROP TABLE IF EXISTS public.departaments;
DROP TABLE IF EXISTS public.authorities;
DROP FUNCTION IF EXISTS public.switch_stats(p_token character varying, p_switch character varying);
DROP FUNCTION IF EXISTS public.session_is_valid(p_session_id character varying);
DROP FUNCTION IF EXISTS public.logout(p_login character varying, p_session_id character varying);
DROP FUNCTION IF EXISTS public.hash_password(p_password character varying);
DROP FUNCTION IF EXISTS public.get_stats_switch(p_token character varying);
DROP FUNCTION IF EXISTS public.get_max_salary_fio();
DROP FUNCTION IF EXISTS public.authorize(p_login character varying, p_password character varying);
DROP FUNCTION IF EXISTS public.add_stats(p_token character varying, p_value character varying);
