
package rnk.l10.soap.ws;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StaffUtils", targetNamespace = "urn://rnk.l10.soap")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StaffUtils {


    /**
     * 
     * @return
     *     returns double
     * @throws RnkWebServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    @Action(input = "urn://rnk.l10.soap:StaffUtils:getMinSalaryRequest", output = "urn://rnk.l10.soap:StaffUtils:getMinSalaryResponse", fault = {
        @FaultAction(className = RnkWebServiceException_Exception.class, value = "urn://rnk.l10.soap:StaffUtils:getMinSalary:Fault:RnkWebServiceException")
    })
    public double getMinSalary()
        throws RnkWebServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns double
     * @throws RnkWebServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    @Action(input = "urn://rnk.l10.soap:StaffUtils:getAvgSalaryRequest", output = "urn://rnk.l10.soap:StaffUtils:getAvgSalaryResponse", fault = {
        @FaultAction(className = RnkWebServiceException_Exception.class, value = "urn://rnk.l10.soap:StaffUtils:getAvgSalary:Fault:RnkWebServiceException")
    })
    public double getAvgSalary()
        throws RnkWebServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns double
     * @throws RnkWebServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    @Action(input = "urn://rnk.l10.soap:StaffUtils:getMaxSalaryRequest", output = "urn://rnk.l10.soap:StaffUtils:getMaxSalaryResponse", fault = {
        @FaultAction(className = RnkWebServiceException_Exception.class, value = "urn://rnk.l10.soap:StaffUtils:getMaxSalary:Fault:RnkWebServiceException")
    })
    public double getMaxSalary()
        throws RnkWebServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.String
     * @throws RnkWebServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    @Action(input = "urn://rnk.l10.soap:StaffUtils:getPersonWithMaxSalaryRequest", output = "urn://rnk.l10.soap:StaffUtils:getPersonWithMaxSalaryResponse", fault = {
        @FaultAction(className = RnkWebServiceException_Exception.class, value = "urn://rnk.l10.soap:StaffUtils:getPersonWithMaxSalary:Fault:RnkWebServiceException")
    })
    public String getPersonWithMaxSalary()
        throws RnkWebServiceException_Exception
    ;

}
