
package rnk.l10.soap.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "RnkWebServiceException", targetNamespace = "urn://rnk.l10.soap")
public class RnkWebServiceException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private RnkWebServiceException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public RnkWebServiceException_Exception(String message, RnkWebServiceException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public RnkWebServiceException_Exception(String message, RnkWebServiceException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: rnk.l10.soap.ws.RnkWebServiceException
     */
    public RnkWebServiceException getFaultInfo() {
        return faultInfo;
    }

}
