
package rnk.l10.soap.ws;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StaffAccounter", targetNamespace = "http://soap.l10.rnk/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StaffAccounter {


    /**
     * 
     * @return
     *     returns double
     * @throws RnkWebServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    @Action(input = "http://soap.l10.rnk/StaffAccounter/getMinSalaryRequest", output = "http://soap.l10.rnk/StaffAccounter/getMinSalaryResponse", fault = {
        @FaultAction(className = RnkWebServiceException_Exception.class, value = "http://soap.l10.rnk/StaffAccounter/getMinSalary/Fault/RnkWebServiceException")
    })
    public double getMinSalary()
        throws RnkWebServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns double
     * @throws RnkWebServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    @Action(input = "http://soap.l10.rnk/StaffAccounter/getMaxSalaryRequest", output = "http://soap.l10.rnk/StaffAccounter/getMaxSalaryResponse", fault = {
        @FaultAction(className = RnkWebServiceException_Exception.class, value = "http://soap.l10.rnk/StaffAccounter/getMaxSalary/Fault/RnkWebServiceException")
    })
    public double getMaxSalary()
        throws RnkWebServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns double
     * @throws RnkWebServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    @Action(input = "http://soap.l10.rnk/StaffAccounter/getAvgSalaryRequest", output = "http://soap.l10.rnk/StaffAccounter/getAvgSalaryResponse", fault = {
        @FaultAction(className = RnkWebServiceException_Exception.class, value = "http://soap.l10.rnk/StaffAccounter/getAvgSalary/Fault/RnkWebServiceException")
    })
    public double getAvgSalary()
        throws RnkWebServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.String
     * @throws RnkWebServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    @Action(input = "http://soap.l10.rnk/StaffAccounter/getPersonWithMaxSalaryRequest", output = "http://soap.l10.rnk/StaffAccounter/getPersonWithMaxSalaryResponse", fault = {
        @FaultAction(className = RnkWebServiceException_Exception.class, value = "http://soap.l10.rnk/StaffAccounter/getPersonWithMaxSalary/Fault/RnkWebServiceException")
    })
    public String getPersonWithMaxSalary()
        throws RnkWebServiceException_Exception
    ;

}
