
package rnk.l10.soap.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StaffAccounterWebService", targetNamespace = "urn://rnk.l10.soap", wsdlLocation = "http://xjabber:18080/staffutils?wsdl")
public class StaffUtilsWebService
    extends Service
{

    private final static URL STAFFUTILSWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException STAFFUTILSWEBSERVICE_EXCEPTION;
    private final static QName STAFFUTILSWEBSERVICE_QNAME = new QName("urn://rnk.l10.soap", "StaffAccounterWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://xjabber:18080/staffutils?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STAFFUTILSWEBSERVICE_WSDL_LOCATION = url;
        STAFFUTILSWEBSERVICE_EXCEPTION = e;
    }

    public StaffUtilsWebService() {
        super(__getWsdlLocation(), STAFFUTILSWEBSERVICE_QNAME);
    }

    public StaffUtilsWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STAFFUTILSWEBSERVICE_QNAME, features);
    }

    public StaffUtilsWebService(URL wsdlLocation) {
        super(wsdlLocation, STAFFUTILSWEBSERVICE_QNAME);
    }

    public StaffUtilsWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STAFFUTILSWEBSERVICE_QNAME, features);
    }

    public StaffUtilsWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StaffUtilsWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StaffAccounter
     */
    @WebEndpoint(name = "staffutils")
    public StaffUtils getStaffutils() {
        return super.getPort(new QName("urn://rnk.l10.soap", "staffutils"), StaffUtils.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StaffAccounter
     */
    @WebEndpoint(name = "staffutils")
    public StaffUtils getStaffutils(WebServiceFeature... features) {
        return super.getPort(new QName("urn://rnk.l10.soap", "staffutils"), StaffUtils.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STAFFUTILSWEBSERVICE_EXCEPTION!= null) {
            throw STAFFUTILSWEBSERVICE_EXCEPTION;
        }
        return STAFFUTILSWEBSERVICE_WSDL_LOCATION;
    }

}
